steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 
          'us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/hello-world-python:$SHORT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',  'us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/hello-world-python:$SHORT_SHA']

- name: 'gcr.io/cloud-builders/docker'
  id: 'update-deployment'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
      sed -i "s|image: flask-app:latest|image: us-central1-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/hello-world-python:${SHORT_SHA}|g" deployment.yaml
      msg=$(git log -1 --pretty=%s)
      echo $msg
      echo "active:$msg:$(basename $REPO_FULL_NAME):${SHORT_SHA}" 
      echo $(basename $REPO_FULL_NAME)
     


- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=${_DEPLOYMENT}
  - --image=us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/hello-world-python:$SHORT_SHA
  - --location=${_LOCATION}
  - --cluster=$_CLUSTER

- name: 'gcr.io/cloud-builders/git'
  id: 'linux'
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
    mkdir -R ~/.ssh
    cat $_SSH_KEY > ~/.ssh/id_rsa
    ls -la ~/.ssh/
    chmod 600 ~/.ssh/id_rsa
    ssh-keyscan github.com >> ~/.ssh/known_hosts
    git clone git@github.com:Adenilson365/testes-helm.git
    cd ./testes-helm
    ls -la

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE: 'us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/hello-world-python:$SHORT_SHA'
  _DEPLOYMENT: 'deployment.yaml'
  _LOCATION: 'us-east1'

images:
- us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/hello-world-python:$SHORT_SHA


