steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'build'
  args: ['build', '-t', 
          'us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/hello-world-python:$SHORT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/hello-world-python:$SHORT_SHA']

- name: 'gcr.io/cloud-builders/docker'
  id: 'update-deployment'
  volumes:
    - name: 'ssh'
      path: '/ssh'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
        mkdir -p /ssh
        sed -i "s|image: flask-app:latest|image: us-central1-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/hello-world-python:${SHORT_SHA}|g" deployment.yaml
        msg=$(git log -1 --pretty=%s)
        echo $msg
        echo "active:$msg:$(basename $REPO_FULL_NAME):${SHORT_SHA}" 
        echo $(basename $REPO_FULL_NAME)
        echo ${SHORT_SHA} >> /ssh/version.txt

- name: 'gcr.io/cloud-builders/git'
  id: 'linux'
  volumes:
    - name: 'ssh'
      path: '/root/.ssh'
  entrypoint: 'bash'
  args: 
    - '-c'
    - |
      whoami
      cat /ssh/version.txt
      mkdir -p ~/.ssh
      echo "${_SSH_KEY}" > ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa

      eval "$(ssh-agent -s)"
      ssh-add ~/.ssh/id_rsa

     ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts

      git clone git@bitbucket.org:teste-gcp/teste-build.git
      git config --global user.email "adekonzelmann@gmail.com"
      git config --global user.name "Cloud Build"    

      cd ./teste-build
      ls -a
      git pull origin main 
      echo "active:msg:build" >> version.txt
      git add ./version.txt
      git commit -m "active:msg"   
      git push origin main

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE: 'us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/hello-world-python:$SHORT_SHA'
  _DEPLOYMENT: 'deployment.yaml'
  _LOCATION: 'us-east1'

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/hello-world-python:$SHORT_SHA
