steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 
          'us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/hello-world-python:$SHORT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',  'us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/hello-world-python:$SHORT_SHA']

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
      sed -i "s|image: flask-app:latest|image: us-central1-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/hello-world-python:${SHORT_SHA}|g" deployment.yaml


- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=${_DEPLOYMENT}
  - --image=us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/hello-world-python:$SHORT_SHA
  - --location=${_LOCATION}
  - --cluster=${_CLUSTER}


options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE: 'us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/hello-world-python:$SHORT_SHA'
  _DEPLOYMENT: 'deployment.yaml'
  _LOCATION: 'us-east1'
  _CLUSTER: 'autopilot-cluster-2'

images:
- us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/hello-world-python:$SHORT_SHA


